#!/usr/bin/env python3
"""Generates src/AggregateTie.generated.hpp.

A structured binding's arity ("auto& [a, b, c] = obj;") is part of its
syntax, not a template parameter -- there is no way to write
"auto& [a...] = obj;" generically over a compile-time N in standard
C++20. So the one piece of automatic aggregate reflection that can't be
templated is mechanically generated here instead: one TieMembers()
overload per N, tag-dispatched on std::integral_constant<size_t, N>.

Regenerate after changing MAX_FIELDS:
    python3 tools/generate_aggregate_tie.py > src/AggregateTie.generated.hpp

See docs/adr/0001-reflection-generation-strategy.md.
"""

MAX_FIELDS = 64

HEADER = """// AUTO-GENERATED by tools/generate_aggregate_tie.py -- do not edit by hand.
// Regenerate with: python3 tools/generate_aggregate_tie.py > src/AggregateTie.generated.hpp
//
// Provides TieMembers(T&, std::integral_constant<std::size_t, N>) for
// N = 0..{max_fields}, each decomposing T via a structured binding of
// exactly N names and returning a std::tie() of references to them.
// See docs/adr/0001-reflection-generation-strategy.md for why this file
// exists and can't be a plain template.
#pragma once

#include <cstddef>
#include <tuple>
#include <type_traits>

namespace reflect::detail {{

template <typename T>
inline auto TieMembers(T&, std::integral_constant<std::size_t, 0>) {{
    return std::tuple<>{{}};
}}
""".format(max_fields=MAX_FIELDS)


def make_overload(n: int) -> str:
    names = [f"a{i}" for i in range(n)]
    binding = ", ".join(names)
    tie_args = ", ".join(names)
    return (
        f"\ntemplate <typename T>\n"
        f"inline auto TieMembers(T& probe, std::integral_constant<std::size_t, {n}>) {{\n"
        f"    auto& [{binding}] = probe;\n"
        f"    return std::tie({tie_args});\n"
        f"}}\n"
    )


def main() -> None:
    parts = [HEADER]
    for n in range(1, MAX_FIELDS + 1):
        parts.append(make_overload(n))
    parts.append("\n} // namespace reflect::detail\n")
    print("".join(parts), end="")


if __name__ == "__main__":
    main()
