#pragma once

#include "TypeInfo.hpp"

#include <cstddef>
#include <utility>

// Registration DSL. See docs/adr/0001 (why macros), docs/adr/0005
// (enum/bit-flag semantics), and docs/adr/0010 for the ordering rule:
// a member's type must be REFLECT_*'d earlier in the translation unit
// than the struct that embeds it.
//
// Usage:
//   struct Vec3 { float x, y, z; };
//   REFLECT_CLASS_BEGIN(Vec3)
//       REFLECT_MEMBER(x)
//       REFLECT_MEMBER(y)
//       REFLECT_MEMBER(z)
//   REFLECT_CLASS_END()

#define REFLECT_CLASS_BEGIN(Type)                                            \
    template <>                                                              \
    struct reflect::TypeInfo<Type> {                                         \
        using ReflectedT = Type;                                             \
        static ::reflect::ClassReflection Describe() {                       \
            ::reflect::ClassReflection r;                                    \
            r.name = r.type = #Type;                                         \
            r.size = static_cast<std::uint32_t>(sizeof(Type));               \
            r.count = 1;

#define REFLECT_MEMBER(Member)                                               \
            {                                                                \
                ::reflect::ClassReflection m =                               \
                    ::reflect::Reflect<decltype(ReflectedT::Member)>();      \
                m.name = #Member;                                            \
                m.offset = static_cast<std::uint32_t>(                       \
                    offsetof(ReflectedT, Member));                           \
                r.members.push_back(std::move(m));                           \
            }

#define REFLECT_CLASS_END()                                                  \
            return r;                                                        \
        }                                                                    \
    };

// DWARF-based registration: generated by
// tools/generate_dwarf_reflection.py from a compiled object's debug
// info (see docs/adr/0013-dwarf-based-reflection-generation.md) --
// not meant to be hand-written. Unlike REFLECT_CLASS_BEGIN/
// REFLECT_MEMBER, every value here (name, type name, offset, size) is
// a LITERAL, never a C++ expression referencing the real member
// (no `decltype(Type::member)`, no `offsetof(Type, member)`). That is
// precisely what makes this reach members REFLECT_MEMBER cannot: it
// never writes an access-checked expression, so it works identically
// for public and private members alike -- DWARF itself doesn't
// distinguish them either.
//
// Usage (normally generated, shown here for reference):
//   REFLECT_DWARF_CLASS_BEGIN(8, "PoorPoint", PoorPoint)
//       REFLECT_DWARF_MEMBER("x", "int", 0, 4, 1)
//       REFLECT_DWARF_MEMBER("y", "int", 4, 4, 1)
//   REFLECT_DWARF_CLASS_END()
//
// Count is 1 for an ordinary member; for a fixed-size array member
// (e.g. "int[4]") it's the real element count (4), read from DWARF's
// DW_TAG_subrange_type the same way Size is -- see
// docs/adr/0013-dwarf-based-reflection-generation.md's "Array-member
// bug found and fixed".
//
// The actual type is the LAST, variadic (...) argument, not the
// first -- deliberate, not stylistic: a template instantiation like
// "Pair<int, float>" contains a top-level comma the C preprocessor
// would otherwise split on when parsing macro arguments (angle
// brackets don't protect a comma the way parentheses do). As the
// trailing __VA_ARGS__, everything after Name is captured verbatim,
// comma and all. Name is a separate, explicit string literal (not
// derived via #Type stringification) for the same reason -- Python
// already knows the exact name to emit and does so directly, the same
// way REFLECT_DWARF_MEMBER's Name/TypeName always have been. See
// docs/adr/0013-dwarf-based-reflection-generation.md's "Fixed bugs".

#define REFLECT_DWARF_CLASS_BEGIN(ByteSize, Name, ...)                       \
    template <>                                                              \
    struct reflect::TypeInfo<__VA_ARGS__> {                                  \
        static ::reflect::ClassReflection Describe() {                       \
            ::reflect::ClassReflection r;                                    \
            r.name = r.type = Name;                                          \
            r.size = static_cast<std::uint32_t>(ByteSize);                   \
            r.count = 1;

#define REFLECT_DWARF_MEMBER(Name, TypeName, Offset, Size, Count)            \
            {                                                                \
                ::reflect::ClassReflection m;                                \
                m.name = Name;                                               \
                m.type = TypeName;                                           \
                m.offset = static_cast<std::uint32_t>(Offset);               \
                m.size = static_cast<std::uint32_t>(Size);                   \
                m.count = static_cast<std::uint32_t>(Count);                 \
                r.members.push_back(std::move(m));                           \
            }

#define REFLECT_DWARF_CLASS_END()                                           \
            return r;                                                        \
        }                                                                    \
    };

#define REFLECT_ENUM_BEGIN(Type)                                             \
    template <>                                                              \
    struct reflect::TypeInfo<Type> {                                         \
        using ReflectedT = Type;                                             \
        static ::reflect::ClassReflection Describe() {                       \
            ::reflect::ClassReflection r;                                    \
            r.name = r.type = r.enum_name = #Type;                           \
            r.size = static_cast<std::uint32_t>(sizeof(Type));               \
            r.count = 1;                                                     \
            r.bit_flag = false;

#define REFLECT_BITFLAG_ENUM_BEGIN(Type)                                     \
    REFLECT_ENUM_BEGIN(Type)                                                 \
            r.bit_flag = true;

#define REFLECT_ENUM_VALUE(Value)                                            \
            r.enum_values[#Value] = static_cast<std::int64_t>(ReflectedT::Value);

#define REFLECT_ENUM_END()                                                   \
            ::reflect::detail::ValidateEnum(r);                              \
            return r;                                                        \
        }                                                                    \
    };
